// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc6-mjSPdvvum2QEOxJkd1yvas0MywpSM',
    appId: '1:722081025698:web:9f1732a5e6bf8abfbe91fb',
    messagingSenderId: '722081025698',
    projectId: 'ayosh-825df',
    authDomain: 'ayosh-825df.firebaseapp.com',
    storageBucket: 'ayosh-825df.appspot.com',
    measurementId: 'G-HCQYBKRKEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv7yGc7MSm6UlmADKPSJKW8v1SyfePVpI',
    appId: '1:722081025698:android:5d6b20d9fe3dd916be91fb',
    messagingSenderId: '722081025698',
    projectId: 'ayosh-825df',
    storageBucket: 'ayosh-825df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4MT_mnDWvxzSnVuHYUAUH5RXaqbsci80',
    appId: '1:722081025698:ios:58ae69739ffaf6fbbe91fb',
    messagingSenderId: '722081025698',
    projectId: 'ayosh-825df',
    storageBucket: 'ayosh-825df.appspot.com',
    iosClientId: '722081025698-5mo8e45807mmfuimm5e9igl38r5lut4g.apps.googleusercontent.com',
    iosBundleId: 'com.mohand.ayooshshein',
  );
}
